const lineOne = document.getElementById('rOne');
const lineTwo = document.getElementById('rTwo');
const lineThree = document.getElementById('rThree');
const lineFour = document.getElementById('rFour');
const lineFive = document.getElementById('rFive');
const lineSix = document.getElementById('rSix');
const lineSeven = document.getElementById('srOne');
const lineEight = document.getElementById('srTwo');
const lineNine = document.getElementById('srThree');
const lineTen = document.getElementById('srFour');
const counterOne = document.getElementById('rOne-count');
const counterTwo = document.getElementById('rTwo-Count');
const counterThree = document.getElementById('rThree-Count');
const counterFour = document.getElementById('rFour-Count');
const counterFive = document.getElementById('rFive-Count');
const counterSix = document.getElementById('rSix-Count');
const counterSeven = document.getElementById('srOne-Count');
const counterEight = document.getElementById('srTwo-Count');
const counterNine = document.getElementById('srThree-Count');
const counterTen = document.getElementById('srFour-Count');

lineOne.addEventListener('input', () => counterOne.textContent = lineOne.value.length);
lineTwo.addEventListener('input', () => counterTwo.textContent = lineTwo.value.length);
lineThree.addEventListener('input', () => counterThree.textContent = lineThree.value.length);
lineFour.addEventListener('input', () => counterFour.textContent = lineFour.value.length);
lineFive.addEventListener('input', () => counterFive.textContent = lineFive.value.length);
lineSix.addEventListener('input', () => counterSix.textContent = lineSix.value.length);
lineSeven.addEventListener('input', () => counterSeven.textContent = lineSeven.value.length);
lineEight.addEventListener('input', () => counterEight.textContent = lineEight.value.length);
lineNine.addEventListener('input', () => counterNine.textContent = lineNine.value.length);
lineTen.addEventListener('input', () => counterTen.textContent = lineTen.value.length);